### ISSUE TITLE
Add Create Mural form

### ISSUE THREAD

**Issue by tedspare** [hack4impact-mcgill/mu-map#66]
- Start from the Material UI [FormGroup](https://material-ui.com/api/form-group/#formgroup-api) and [TextField](https://material-ui.com/api/form-group/#formgroup-api) components
- Run the backend and ensure you can create a mural in Postman via the `POST` `/mural` endpoint
- Replicate this API call in your component using [Axios](https://kapeli.com/cheat_sheets/Axios.docset/Contents/Resources/Documents/index)
- To look up an address and convert it to coordinates, we will use the [MapBox Geocoder](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/). Same API key as for the `Map`. If it's too hard, leave this for later!
- See the [mockup](https://www.figma.com/file/1C71g93ZA1yFWchMa4id7J/MU-Map-2020-21?node-id=209%3A6029) for appearance (all fields should actually be flat `TextFields`). Ignore image uploads for now. Create issues or tell the PM about any fields which are missing from the backend.
- ![image](https://user-images.githubusercontent.com/36117635/103806104-8aa34c80-5022-11eb-891b-814cd2ddf3f3.png)

**Comment by JDziewonski98** [comment]
1. The fields in the mockup and the backend model do not match up. Backend has city, neighborhood, and borough, which the mockup does not have. The mockup has social media, which backend does not have. Which fields should we actually have?

2. Since we have borough and artist as a separate entity that mural refers to, we need to make sure that a valid artist and borough is entered in the input of the mural creation. Perhaps create a new issue for a reusable text field component that lets you search / select from valid options?

3. For a field like 'assistants', maybe a new issue should be made to create a reusable component for that as well? I assume we want it to be : press + => new text field appears => enter text and press ok => your entry appears as a new row under "assistants" with a delete button next to it? Maybe material ui has something for this?

**Comment by tedspare** [comment]
@JDziewonski98 

1. What do you think about city, neighborhood, and borough being calculated/inferred from the address and geocoder? Social media links will have to be added to the Mural model.
2. Blanche's [use](https://github.com/hack4impact-mcgill/mu-map/pull/69/files#diff-5dcdfbedcc21bfd2bc210719a6f1d8bcc2a71637b4281da18d801e13e11ba65d) of the MUI Autocomplete component can serve as an example. This could be extended with an "Add new artist" button for empty search results. This is covered by the Autocomplete component [here](https://material-ui.com/components/autocomplete/#creatable).
3. I would agree. To keep this issue narrow and feasible lol let's just ignore it for now and maybe include "next steps" in your PR and I'll turn them into issues. Your flow makes sense to me. It could be achieved with a `useState(['assistant1'])` with `useCallback()`s for adding and deleting

**Comment by JDziewonski98** [comment]
1. It looks like  the geocoder gives you a city and neighborhood packaged with an address, but i'm still unsure about neighborhood / borough. We have borough as a separate table, do we want borough to be manually generated and referenced, with neighborhood inferred by mapbox from the address?

**Comment by tedspare** [comment]
1. That makes sense to me. We confirmed with Lea that boroughs are static and well-defined whereas neighbourhoods are less formal.

**Comment by tedspare** [comment]
Closed by #76
